version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ag_agenda_mongodb
    ports:
      - '27020:27017'
    volumes:
      - ag_agenda_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ag_agenda

volumes:
  ag_agenda_data:
